services:
  smart-schedule-mysql:
    image: mysql:8.0
    container_name: smart-schedule-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smart-schedule-network

  smart-schedule-redis:
    image: 'redis:alpine'
    container_name: smart-schedule-redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - smart-schedule-network
networks:
  smart-schedule-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
